package app;

import java.io.IOException;
import java.math.BigDecimal;
import java.nio.charset.StandardCharsets;
import java.nio.file.AtomicMoveNotSupportedException;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.StandardCopyOption;
import java.util.ArrayList;
import java.util.Collections;
import java.util.LinkedHashMap;
import java.util.LinkedHashSet;
import java.util.List;
import java.util.Locale;
import java.util.Map;
import java.util.Optional;
import java.util.Set;
import java.util.regex.Matcher;
import java.util.regex.Pattern;

/**
 * Runtime data store for any top-level collection literal in {@code app.py}
 * (for example {@code products}, {@code posts} or {@code books}). The Python
 * source is read-only at runtime: create/update/delete operations persist to a
 * sidecar JSON file in {@code <project>/data/&lt;collection&gt;.json} instead of
 * editing app.py.
 *
 * <p>The app.py literal acts as the seed and the schema source. The store
 * layers the sidecar over it on every read: records with the same {@code "id"}
 * take the JSON version, records present only in JSON are added, records
 * present only in the literal are kept, and ids listed in {@code "deleted"} are
 * suppressed (so UI deletions are not resurrected by the seed).</p>
 *
 * <p>app.py is never rewritten automatically. {@link #clearRuntimeData(Path)}
 * wipes every {@code data/*.json} sidecar at program start and after any
 * watcher-triggered recompile (a source change), so the app always boots from
 * the literal and the sidecars live only for the current session.
 * {@link #absorbDataIntoSource(Path)} remains available as a manual utility that
 * folds the sidecar back into the literal.</p>
 *
 * <p>The dictionary schema (field order and value types) is inferred from the
 * records, so no field set is hard-coded. The {@code "id"} field is the numeric
 * key used for updates and deletes. The literal reader tolerates {@code #} line
 * comments inside the collection; comments never appear in the sidecar and are
 * dropped only when the literal is regenerated by the manual absorb utility.</p>
 */
public final class PythonDataStore {

    /** Kind of a value in a record. */
    private enum FieldKind { STRING, NUMBER, BOOLEAN, RAW }

    private record Schema(List<String> order, Map<String, FieldKind> kinds) {
    }

    private record Parsed(List<DataRecord> records, Schema schema) {
    }

    private record Load(List<DataRecord> records, Schema schema, Set<Integer> deleted) {
    }

    private record JsonData(List<DataRecord> records, Set<Integer> deleted) {
    }

    private record Key(String name, int nextIndex) {
    }

    private record Value(Object typedValue, FieldKind kind, String rawText, int nextIndex) {
    }

    private final Path pythonSource;
    private final Path dataFile;
    private final String collectionName;
    private final Pattern assignmentPattern;

    private static final Pattern PYTHON_INTEGER = Pattern.compile(
            "-?\\d+([eE][+-]?\\d+)?");
    private static final Pattern PYTHON_NUMBER = Pattern.compile(
            "-?(\\d+\\.\\d*|\\.\\d+|\\d+)([eE][+-]?\\d+)?");
    private static final Pattern TOP_LEVEL_ASSIGNMENT = Pattern.compile(
            "(?m)^\\s*([A-Za-z_][A-Za-z0-9_]*)\\s*=\\s*\\[");

    public PythonDataStore(Path pythonSource, String collectionName) {
        this.pythonSource = pythonSource.toAbsolutePath().normalize();
        this.collectionName = collectionName;
        this.assignmentPattern = Pattern.compile(
                "(?m)^" + Pattern.quote(collectionName) + "\\s*=\\s*\\[");
        this.dataFile = this.pythonSource.getParent().resolve("data")
                .resolve(collectionName + ".json").normalize();
    }

    public String collectionName() {
        return collectionName;
    }

    public synchronized List<DataRecord> list() throws IOException {
        return load().records();
    }

    /** Records rendered as plain maps (including the {@code "id"} key) for the Jinja renderer. */
    public synchronized List<Map<String, Object>> listAsMaps() throws IOException {
        List<Map<String, Object>> maps = new ArrayList<>();
        for (DataRecord record : load().records()) {
            maps.add(record.fields());
        }
        return maps;
    }

    public synchronized Optional<DataRecord> find(int id) throws IOException {
        for (DataRecord record : load().records()) {
            if (record.id() == id) {
                return Optional.of(record);
            }
        }
        return Optional.empty();
    }

    public synchronized DataRecord create(Map<String, String> form) throws IOException {
        Load load = load();
        List<DataRecord> records = new ArrayList<>(load.records());
        int nextId = records.stream().map(DataRecord::id)
                .max(Integer::compareTo).orElse(0) + 1;
        Map<String, Object> values = coerceFields(load.schema(), nextId, form);
        DataRecord created = new DataRecord(nextId, values);
        records.add(created);
        writeDataFile(records, new LinkedHashSet<>(load.deleted()));
        return created;
    }

    public synchronized DataRecord update(int id, Map<String, String> form) throws IOException {
        Load load = load();
        List<DataRecord> records = new ArrayList<>(load.records());
        int index = -1;
        for (int i = 0; i < records.size(); i++) {
            if (records.get(i).id() == id) {
                index = i;
                break;
            }
        }
        if (index < 0) {
            throw new NotFoundException(collectionName, id);
        }
        Map<String, Object> values = coerceFields(load.schema(), id, form);
        records.set(index, new DataRecord(id, values));
        writeDataFile(records, new LinkedHashSet<>(load.deleted()));
        return new DataRecord(id, values);
    }

    public synchronized void delete(int id) throws IOException {
        Load load = load();
        List<DataRecord> records = new ArrayList<>(load.records());
        boolean removed = records.removeIf(record -> record.id() == id);
        if (!removed) {
            throw new NotFoundException(collectionName, id);
        }
        Set<Integer> deleted = new LinkedHashSet<>(load.deleted());
        deleted.add(id);
        writeDataFile(records, deleted);
    }

    // ------------------------------------------------------------------
    // Compiler-side absorption: merge the sidecar back into app.py.
    // ------------------------------------------------------------------

    /**
     * Manual utility: merges every editable {@code name = [...]} collection's
     * sidecar back into the app.py literal and resyncs the sidecar. NOT invoked
     * by the compiler or watcher anymore - app.py is left untouched at runtime
     * and on recompiles. Kept for an explicit, user-invoked "bake into source".
     */
    public static void absorbDataIntoSource(Path projectDir) throws IOException {
        Path appPy = projectDir.resolve("app.py");
        if (!Files.isRegularFile(appPy)) {
            return;
        }
        String source = Files.readString(appPy, StandardCharsets.UTF_8);
        Set<String> names = new LinkedHashSet<>();
        Matcher matcher = TOP_LEVEL_ASSIGNMENT.matcher(source);
        while (matcher.find()) {
            names.add(matcher.group(1));
        }
        for (String name : names) {
            try {
                new PythonDataStore(appPy, name).absorb();
            } catch (IOException e) {
                System.err.println("  SKIP data absorption for '" + name + "': " + e.getMessage());
            }
        }
    }

    /** Removes every runtime sidecar ({@code data/*.json}) for the project, so a recompile
     *  falls back to app.py as the sole source of truth. Called for watcher-triggered
     *  compiles (never at startup, which absorbs instead). */
    public static void clearRuntimeData(Path projectDir) throws IOException {
        Path dataDir = projectDir.resolve("data");
        if (!Files.isDirectory(dataDir)) {
            return;
        }
        try (var files = Files.list(dataDir)) {
            for (Path file : files.toList()) {
                if (file.getFileName().toString().endsWith(".json")) {
                    Files.deleteIfExists(file);
                }
            }
        }
    }

    /** Merges the sidecar (if any) into this collection's literal and resyncs the sidecar. */
    private void absorb() throws IOException {
        Parsed parsed;
        try {
            parsed = parseSource();
        } catch (IOException e) {
            // Not an editable collection (plain list, malformed literal, ...) - leave it alone.
            return;
        }
        boolean hasData = Files.isRegularFile(dataFile);
        if (!hasData) {
            // No runtime mutations: the literal is already authoritative; do not
            // rewrite app.py or create a sidecar for a collection that was never edited.
            return;
        }
        Load load = merge(parsed.records(), readDataFile());
        String source = Files.readString(pythonSource, StandardCharsets.UTF_8);
        String rewritten = rewriteLiteral(source, load.records(), load.schema());
        if (!rewritten.equals(source)) {
            writeAtomically(pythonSource, rewritten);
        }
        // The literal is now authoritative; tombstones no longer needed.
        writeDataFile(load.records(), Collections.emptySet());
    }

    private String rewriteLiteral(String source, List<DataRecord> records, Schema schema) throws IOException {
        int openingBracket = findOpeningBracket(source);
        int closingBracket = findMatchingBracket(source, openingBracket);
        String renderedList = renderList(schema, records);
        return source.substring(0, openingBracket) + renderedList + source.substring(closingBracket + 1);
    }

    // ------------------------------------------------------------------
    // Reading: app.py literal (seed) merged with the sidecar data file.
    // ------------------------------------------------------------------

    private Load load() throws IOException {
        Parsed parsed = parseSource();
        if (!Files.isRegularFile(dataFile)) {
            return new Load(parsed.records(), parsed.schema(), Collections.emptySet());
        }
        return merge(parsed.records(), readDataFile());
    }

    /** Sidecar wins per id; literal-only records are kept; tombstoned ids are dropped. */
    private static Load merge(List<DataRecord> base, JsonData data) {
        Map<Integer, DataRecord> jsonById = new LinkedHashMap<>();
        for (DataRecord record : data.records()) {
            jsonById.put(record.id(), record);
        }
        List<DataRecord> merged = new ArrayList<>(data.records());
        for (DataRecord record : base) {
            if (jsonById.containsKey(record.id()) || data.deleted().contains(record.id())) {
                continue;
            }
            merged.add(record);
        }
        return new Load(List.copyOf(merged), schemaOf(merged), data.deleted());
    }

    private Parsed parseSource() throws IOException {
        String source = Files.readString(pythonSource, StandardCharsets.UTF_8);
        int openingBracket = findOpeningBracket(source);
        int closingBracket = findMatchingBracket(source, openingBracket);
        String body = source.substring(openingBracket + 1, closingBracket);
        return parseBody(body);
    }

    private Parsed parseBody(String body) throws IOException {
        List<DataRecord> records = new ArrayList<>();
        int index = 0;
        while (true) {
            index = skipWsAndComments(body, index);
            if (index >= body.length()) {
                break;
            }
            char current = body.charAt(index);
            if (current == ',') {
                index++;
                continue;
            }
            if (current != '{') {
                throw new IOException("Unexpected content in the '" + collectionName
                        + "' literal in app.py: ensure each entry is a dict literal.");
            }
            ParsedDict parsedDict = parseDict(body, index);
            index = parsedDict.nextIndex();
            if (parsedDict.id() == null) {
                throw new IOException("Each item in '" + collectionName
                        + "' in app.py must contain a numeric \"id\" key.");
            }
            records.add(new DataRecord(parsedDict.id(), parsedDict.values()));
        }
        if (!body.isBlank() && records.isEmpty()) {
            throw new IOException("Could not parse the '" + collectionName
                    + "' list in app.py. Ensure each entry is a dict literal.");
        }
        return new Parsed(List.copyOf(records), schemaOf(records));
    }

    private static Schema schemaOf(List<DataRecord> records) {
        List<String> order = new ArrayList<>();
        Map<String, FieldKind> kinds = new LinkedHashMap<>();
        for (DataRecord record : records) {
            for (Map.Entry<String, Object> entry : record.fields().entrySet()) {
                if (!order.contains(entry.getKey())) {
                    order.add(entry.getKey());
                }
                kinds.merge(entry.getKey(), kindOfValue(entry.getValue()), PythonDataStore::mostSpecificKind);
            }
        }
        return new Schema(List.copyOf(order), Map.copyOf(kinds));
    }

    /** Advances over whitespace and '#' line comments, returning the next meaningful index. */
    private static int skipWsAndComments(String body, int index) {
        while (index < body.length()) {
            char current = body.charAt(index);
            if (current == '#') {
                while (index < body.length()) {
                    char inner = body.charAt(index);
                    if (inner == '\n' || inner == '\r' || inner == '\f') {
                        break;
                    }
                    index++;
                }
            } else if (Character.isWhitespace(current)) {
                index++;
            } else {
                break;
            }
        }
        return index;
    }

    private record ParsedDict(Integer id, Map<String, Object> values, int nextIndex) {
    }

    private ParsedDict parseDict(String body, int startIndex) throws IOException {
        int index = startIndex + 1; // skip the opening '{'
        Integer id = null;
        Map<String, Object> values = new LinkedHashMap<>();
        while (true) {
            index = skipWsAndComments(body, index);
            if (index < body.length() && body.charAt(index) == ',') {
                index++;
                continue;
            }
            if (index >= body.length()) {
                throw new IOException("Unterminated dict literal in '" + collectionName + "'.");
            }
            if (body.charAt(index) == '}') {
                index++;
                break;
            }
            Key key = readKey(body, index);
            index = key.nextIndex();
            index = skipWsAndComments(body, index);
            if (index >= body.length() || body.charAt(index) != ':') {
                throw new IOException("Expected ':' after key '" + key.name() + "' in '" + collectionName + "'.");
            }
            index++;
            index = skipWsAndComments(body, index);
            Value value = readValue(body, index);
            index = value.nextIndex();
            values.put(key.name(), value.typedValue());
            if ("id".equals(key.name())) {
                id = parseIdValue(value, key.name());
            }
        }
        return new ParsedDict(id, values, index);
    }

    private Key readKey(String body, int index) throws IOException {
        char current = body.charAt(index);
        if (current == '"' || current == '\'') {
            Value quoted = readQuoted(body, index);
            return new Key(pythonUnescape(quoted.rawText()), quoted.nextIndex());
        }
        int cursor = index;
        while (cursor < body.length()
                && (Character.isLetterOrDigit(body.charAt(cursor)) || body.charAt(cursor) == '_')) {
            cursor++;
        }
        if (cursor == index) {
            throw new IOException("Invalid key in '" + collectionName + "' literal at index " + index + ".");
        }
        return new Key(body.substring(index, cursor), cursor);
    }

    private Value readValue(String body, int index) throws IOException {
        char current = body.charAt(index);
        if (current == '"' || current == '\'') {
            return readQuoted(body, index);
        }
        int cursor = index;
        int depth = 0;
        StringBuilder raw = new StringBuilder();
        while (cursor < body.length()) {
            char ch = body.charAt(cursor);
            if (ch == '"' || ch == '\'') {
                raw.append(ch);
                cursor++;
                while (cursor < body.length()) {
                    char inner = body.charAt(cursor);
                    raw.append(inner);
                    if (inner == '\\') {
                        if (cursor + 1 < body.length()) {
                            cursor++;
                            raw.append(body.charAt(cursor));
                        }
                    } else if (inner == ch) {
                        cursor++;
                        break;
                    }
                    cursor++;
                }
                continue;
            }
            if (ch == '[' || ch == '{' || ch == '(') {
                depth++;
            } else if (ch == ']' || ch == '}') {
                if (depth == 0) {
                    break;
                }
                depth--;
            } else if (ch == ')' ) {
                if (depth == 0) {
                    break;
                }
                depth--;
            } else if ((ch == ',' || ch == '}' || ch == '#') && depth == 0) {
                break;
            }
            raw.append(ch);
            cursor++;
        }
        String text = raw.toString().trim();
        return classifyRaw(text, cursor);
    }

    private Value classifyRaw(String text, int nextIndex) throws IOException {
        if (!text.isEmpty() && (text.startsWith("\"") || text.startsWith("'"))) {
            throw new IOException("Unexpected quoted value while parsing '" + collectionName + "'.");
        }
        if ("True".equals(text)) {
            return new Value(Boolean.TRUE, FieldKind.BOOLEAN, text, nextIndex);
        }
        if ("False".equals(text)) {
            return new Value(Boolean.FALSE, FieldKind.BOOLEAN, text, nextIndex);
        }
        if (PYTHON_NUMBER.matcher(text).matches()) {
            try {
                BigDecimal number = new BigDecimal(text);
                return new Value(normalizeNumber(number), FieldKind.NUMBER, text, nextIndex);
            } catch (NumberFormatException ignored) {
                // Fall through and treat as a raw expression.
            }
        }
        return new Value(text, FieldKind.RAW, text, nextIndex);
    }

    /** Reads a quoted token; {@code rawText} keeps escapes, excluding the surrounding quotes. */
    private Value readQuoted(String body, int index) throws IOException {
        char quote = body.charAt(index);
        if (index >= body.length()) {
            throw new IOException("Unterminated string in '" + collectionName + "' literal.");
        }
        int cursor = index + 1;
        StringBuilder inner = new StringBuilder();
        boolean escaping = false;
        while (cursor < body.length()) {
            char current = body.charAt(cursor);
            if (escaping) {
                inner.append(current);
                escaping = false;
            } else if (current == '\\') {
                escaping = true;
            } else if (current == quote) {
                cursor++;
                return new Value(pythonUnescape(inner.toString()), FieldKind.STRING, inner.toString(), cursor);
            } else {
                inner.append(current);
            }
            cursor++;
        }
        throw new IOException("Unterminated string literal in '" + collectionName + "'.");
    }

    private int parseIdValue(Value value, String field) throws IOException {
        if (value.kind() == FieldKind.NUMBER && value.typedValue() instanceof BigDecimal decimal) {
            try {
                return decimal.intValueExact();
            } catch (ArithmeticException ignored) {
                throw new IOException("The \"id\" values in '" + collectionName + "' must be integers.");
            }
        }
        String text = value.rawText() == null ? "" : value.rawText().trim();
        if (!PYTHON_INTEGER.matcher(text).matches()) {
            throw new IOException("The \"id\" values in '" + collectionName + "' must be integers.");
        }
        try {
            return Integer.parseInt(text);
        } catch (NumberFormatException e) {
            throw new IOException("The \"id\" values in '" + collectionName + "' must be integers.");
        }
    }

    /** Whole numbers become {@code Long} (clean JSON/rendered output); anything else keeps full precision. */
    private static Object normalizeNumber(BigDecimal number) {
        BigDecimal stripped = number.stripTrailingZeros();
        if (stripped.scale() <= 0 && stripped.precision() - stripped.scale() <= 18) {
            try {
                return stripped.longValueExact();
            } catch (ArithmeticException ignored) {
                // Too large for a long; keep full precision.
            }
        }
        return stripped;
    }

    private static FieldKind kindOfValue(Object value) {
        if (value instanceof BigDecimal || value instanceof Number) {
            return FieldKind.NUMBER;
        }
        if (value instanceof Boolean) {
            return FieldKind.BOOLEAN;
        }
        return FieldKind.STRING;
    }

    private static FieldKind mostSpecificKind(FieldKind existing, FieldKind candidate) {
        // Number/boolean/string precedence is decided on the first occurrence;
        // a field is NUMBER/BOOLEAN only when all rows agree.
        if (existing == candidate) {
            return existing;
        }
        if (existing == FieldKind.RAW) {
            return candidate;
        }
        if (candidate == FieldKind.RAW) {
            return existing;
        }
        return FieldKind.STRING;
    }

    private Map<String, Object> coerceFields(Schema schema, int id, Map<String, String> form) {
        Map<String, Object> values = new LinkedHashMap<>();
        values.put("id", id);
        for (String field : schema.order()) {
            if ("id".equals(field)) {
                continue;
            }
            FieldKind kind = schema.kinds().getOrDefault(field, FieldKind.STRING);
            String raw = form.get(field);
            Object coerced = coerce(kind, field, raw);
            if (coerced != null) {
                values.put(field, coerced);
            }
        }
        return values;
    }

    private Object coerce(FieldKind kind, String field, String raw) {
        switch (kind) {
            case NUMBER:
                if (raw == null || raw.trim().isEmpty()) {
                    throw new IllegalArgumentException("The field '" + field + "' must be a number.");
                }
                try {
                    BigDecimal value = new BigDecimal(raw.trim());
                    return normalizeNumber(value);
                } catch (NumberFormatException e) {
                    throw new IllegalArgumentException("The field '" + field + "' must be a number.");
                }
            case BOOLEAN:
                if (raw == null) {
                    return Boolean.FALSE;
                }
                String lower = raw.trim().toLowerCase(Locale.ROOT);
                return "true".equals(lower) || "1".equals(lower)
                        || "on".equals(lower) || "yes".equals(lower);
            case STRING:
            case RAW:
            default:
                return raw == null ? "" : raw;
        }
    }

    // ------------------------------------------------------------------
    // Sidecar persistence: <project>/data/<collection>.json
    // ------------------------------------------------------------------

    private void writeDataFile(List<DataRecord> records, Set<Integer> deleted) throws IOException {
        Files.createDirectories(dataFile.getParent());
        writeAtomically(dataFile, renderJson(schemaOf(records), records, deleted));
    }

    private static String renderJson(Schema schema, List<DataRecord> records, Set<Integer> deleted) {
        StringBuilder out = new StringBuilder("{\n  \"records\": [\n");
        for (int index = 0; index < records.size(); index++) {
            List<String> parts = new ArrayList<>();
            for (String field : schema.order()) {
                Object value = records.get(index).fields().get(field);
                if (value == null) {
                    continue;
                }
                FieldKind kind = schema.kinds().getOrDefault(field, FieldKind.STRING);
                parts.add(jsonString(field) + ": " + jsonValue(kind, value));
            }
            out.append("    { ").append(String.join(", ", parts)).append(" }");
            if (index < records.size() - 1) {
                out.append(',');
            }
            out.append('\n');
        }
        out.append("  ],\n  \"deleted\": [");
        List<Integer> sorted = new ArrayList<>(deleted);
        Collections.sort(sorted);
        for (int index = 0; index < sorted.size(); index++) {
            out.append(sorted.get(index));
            if (index < sorted.size() - 1) {
                out.append(", ");
            }
        }
        return out.append("]\n}\n").toString();
    }

    private static String jsonValue(FieldKind kind, Object value) {
        switch (kind) {
            case NUMBER:
                if (value instanceof BigDecimal decimal) {
                    return decimal.stripTrailingZeros().toPlainString();
                }
                return String.valueOf(value);
            case BOOLEAN:
                return Boolean.TRUE.equals(value) ? "true" : "false";
            case STRING:
            case RAW:
            default:
                return jsonString(String.valueOf(value));
        }
    }

    private static String jsonString(String value) {
        StringBuilder out = new StringBuilder("\"");
        for (int index = 0; index < value.length(); index++) {
            char current = value.charAt(index);
            switch (current) {
                case '"' -> out.append("\\\"");
                case '\\' -> out.append("\\\\");
                case '\n' -> out.append("\\n");
                case '\r' -> out.append("\\r");
                case '\t' -> out.append("\\t");
                case '\b' -> out.append("\\b");
                case '\f' -> out.append("\\f");
                default -> {
                    if (current < 0x20) {
                        out.append(String.format("\\u%04x", (int) current));
                    } else {
                        out.append(current);
                    }
                }
            }
        }
        return out.append('"').toString();
    }

    /** Reads the sidecar; returns empty data when the file is absent. */
    private JsonData readDataFile() throws IOException {
        if (!Files.isRegularFile(dataFile)) {
            return new JsonData(List.of(), Collections.emptySet());
        }
        String json = Files.readString(dataFile, StandardCharsets.UTF_8);
        Object root = new JsonParser(json).parseValue();
        if (!(root instanceof Map<?, ?> map)) {
            throw new IOException("The '" + collectionName + "' data file (" + dataFile.getFileName()
                    + ") must contain a JSON object with a \"records\" array.");
        }
        List<DataRecord> records = new ArrayList<>();
        Object recordsValue = map.get("records");
        if (recordsValue == null) {
            throw new IOException("The '" + collectionName + "' data file (" + dataFile.getFileName()
                    + ") is missing the \"records\" array.");
        }
        if (!(recordsValue instanceof List<?> list)) {
            throw new IOException("The \"records\" entry in '" + dataFile.getFileName()
                    + "' must be an array.");
        }
        for (Object item : list) {
            if (!(item instanceof Map<?, ?> itemMap)) {
                throw new IOException("Each entry in '" + dataFile.getFileName()
                        + "' must be a JSON object.");
            }
            Map<String, Object> fields = new LinkedHashMap<>();
            Object idValue = null;
            for (Map.Entry<?, ?> entry : itemMap.entrySet()) {
                String field = String.valueOf(entry.getKey());
                Object value = entry.getValue();
                if (value instanceof Map || value instanceof List) {
                    throw new IOException("Only strings, numbers and booleans are supported in '"
                            + dataFile.getFileName() + "' (field '" + field + "').");
                }
                if ("id".equals(field)) {
                    idValue = value;
                }
                fields.put(field, value == null ? "" : value);
            }
            records.add(new DataRecord(jsonId(idValue), fields));
        }

        Set<Integer> deleted = new LinkedHashSet<>();
        Object deletedValue = map.get("deleted");
        if (deletedValue != null) {
            if (!(deletedValue instanceof List<?> deletedList)) {
                throw new IOException("The \"deleted\" entry in '" + dataFile.getFileName()
                        + "' must be an array of ids.");
            }
            for (Object id : deletedList) {
                deleted.add(jsonId(id));
            }
        }
        return new JsonData(List.copyOf(records), deleted);
    }

    private static int jsonId(Object value) throws IOException {
        if (value instanceof Long number) {
            try {
                return Math.toIntExact(number);
            } catch (ArithmeticException e) {
                throw new IOException("An \"id\" in the data file must be a 32-bit integer.");
            }
        }
        if (value instanceof BigDecimal decimal) {
            try {
                return decimal.intValueExact();
            } catch (ArithmeticException e) {
                throw new IOException("An \"id\" in the data file must be a 32-bit integer.");
            }
        }
        throw new IOException("An \"id\" in the data file must be an integer.");
    }

    // ------------------------------------------------------------------
    // Writing: render the merged records back to a Python literal.
    // ------------------------------------------------------------------

    private static String renderList(Schema schema, List<DataRecord> records) {
        if (records.isEmpty()) {
            return "[]";
        }
        StringBuilder out = new StringBuilder("[\n");
        for (int index = 0; index < records.size(); index++) {
            out.append(renderRecord(schema, records.get(index)));
            if (index < records.size() - 1) {
                out.append(',');
            }
            out.append('\n');
        }
        return out.append(']').toString();
    }

    private static String renderRecord(Schema schema, DataRecord record) {
        Map<String, Object> fields = record.fields();
        StringBuilder out = new StringBuilder("    {\n");
        List<String> fieldLines = new ArrayList<>();
        for (String field : schema.order()) {
            Object value = fields.get(field);
            if (value == null) {
                continue;
            }
            FieldKind kind = schema.kinds().getOrDefault(field, FieldKind.STRING);
            String renderedValue = renderValue(kind, value);
            fieldLines.add("        \"" + DataRecord.pythonEscape(field) + "\": " + renderedValue);
        }
        if (fieldLines.isEmpty()) {
            return "    { }";
        }
        for (int index = 0; index < fieldLines.size(); index++) {
            out.append(fieldLines.get(index));
            if (index < fieldLines.size() - 1) {
                out.append(',');
            }
            out.append('\n');
        }
        return out.append("    }").toString();
    }

    private static String renderValue(FieldKind kind, Object value) {
        if (value == null) {
            return "";
        }
        switch (kind) {
            case NUMBER:
                if (value instanceof BigDecimal decimal) {
                    return decimal.stripTrailingZeros().toPlainString();
                }
                return String.valueOf(value);
            case BOOLEAN:
                return Boolean.TRUE.equals(value) ? "True" : "False";
            case RAW:
                return String.valueOf(value);
            case STRING:
            default:
                return "\"" + DataRecord.pythonEscape(String.valueOf(value)) + "\"";
        }
    }

    // ------------------------------------------------------------------
    // Locating and boundary scanning of the collection literal.
    // ------------------------------------------------------------------

    private int findOpeningBracket(String source) throws IOException {
        Matcher matcher = assignmentPattern.matcher(source);
        if (!matcher.find()) {
            throw new IOException("No top-level '" + collectionName
                    + " = [...]' declaration was found in app.py.");
        }
        int bracket = source.indexOf('[', matcher.start());
        if (bracket < 0) {
            throw new IOException("The '" + collectionName + "' declaration in app.py has no '['.");
        }
        return bracket;
    }

    private int findMatchingBracket(String source, int openingBracket) throws IOException {
        int depth = 0;
        boolean inString = false;
        boolean escaping = false;
        char quote = 0;
        for (int index = openingBracket; index < source.length(); index++) {
            char current = source.charAt(index);
            if (inString) {
                if (escaping) {
                    escaping = false;
                } else if (current == '\\') {
                    escaping = true;
                } else if (current == quote) {
                    inString = false;
                }
                continue;
            }
            if (current == '#') {
                while (index < source.length()
                        && source.charAt(index) != '\n' && source.charAt(index) != '\r'
                        && source.charAt(index) != '\f') {
                    index++;
                }
                continue;
            }
            if (current == '\'' || current == '"') {
                inString = true;
                quote = current;
            } else if (current == '[') {
                depth++;
            } else if (current == ']' && --depth == 0) {
                return index;
            }
        }
        throw new IOException("The '" + collectionName + "' list in app.py has no matching closing bracket.");
    }

    // ------------------------------------------------------------------
    // Atomic writes and escaping helpers.
    // ------------------------------------------------------------------

    /** Writes {@code content} to {@code target} atomically, skipping the write when unchanged. */
    private static void writeAtomically(Path target, String content) throws IOException {
        if (Files.isRegularFile(target)) {
            String existing = Files.readString(target, StandardCharsets.UTF_8);
            if (existing.equals(content)) {
                return;
            }
        }
        Path parent = target.getParent();
        Path temporary = Files.createTempFile(parent, target.getFileName() + ".", ".tmp");
        try {
            Files.writeString(temporary, content, StandardCharsets.UTF_8);
            try {
                Files.move(temporary, target, StandardCopyOption.ATOMIC_MOVE, StandardCopyOption.REPLACE_EXISTING);
            } catch (AtomicMoveNotSupportedException ignored) {
                Files.move(temporary, target, StandardCopyOption.REPLACE_EXISTING);
            }
        } finally {
            Files.deleteIfExists(temporary);
        }
    }

    private static String pythonUnescape(String value) {
        StringBuilder out = new StringBuilder();
        boolean escaping = false;
        for (int index = 0; index < value.length(); index++) {
            char current = value.charAt(index);
            if (escaping) {
                switch (current) {
                    case 'n' -> out.append('\n');
                    case 'r' -> out.append('\r');
                    case 't' -> out.append('\t');
                    default -> out.append(current);
                }
                escaping = false;
            } else if (current == '\\') {
                escaping = true;
            } else {
                out.append(current);
            }
        }
        if (escaping) {
            out.append('\\');
        }
        return out.toString();
    }

    /**
     * Minimal JSON reader for the sidecar data file (objects, arrays, strings,
     * numbers, booleans and null, with standard escapes).
     */
    private static final class JsonParser {
        private final String text;
        private int pos;

        JsonParser(String text) {
            this.text = text;
        }

        private IOException error(String message) {
            return new IOException(message + " at data file offset " + pos + ".");
        }

        private void ws() {
            while (pos < text.length() && Character.isWhitespace(text.charAt(pos))) {
                pos++;
            }
        }

        Object parseValue() throws IOException {
            ws();
            if (pos >= text.length()) {
                throw error("Unexpected end of JSON");
            }
            char current = text.charAt(pos);
            switch (current) {
                case '{':
                    return parseObject();
                case '[':
                    return parseArray();
                case '"':
                    return parseString();
                case 't':
                    expect("true");
                    return Boolean.TRUE;
                case 'f':
                    expect("false");
                    return Boolean.FALSE;
                case 'n':
                    expect("null");
                    return null;
                default:
                    if (current == '-' || Character.isDigit(current)) {
                        return parseNumber();
                    }
                    throw error("Unexpected character '" + current + "'");
            }
        }

        private void expect(String literal) throws IOException {
            if (!text.startsWith(literal, pos)) {
                throw error("Expected '" + literal + "'");
            }
            pos += literal.length();
        }

        private Map<String, Object> parseObject() throws IOException {
            Map<String, Object> map = new LinkedHashMap<>();
            pos++; // consume '{'
            ws();
            if (pos < text.length() && text.charAt(pos) == '}') {
                pos++;
                return map;
            }
            while (true) {
                ws();
                if (pos >= text.length() || text.charAt(pos) != '"') {
                    throw error("Expected a quoted key");
                }
                String key = parseString();
                ws();
                if (pos >= text.length() || text.charAt(pos) != ':') {
                    throw error("Expected ':' after '" + key + "'");
                }
                pos++;
                map.put(key, parseValue());
                ws();
                if (pos >= text.length()) {
                    throw error("Unterminated object");
                }
                char separator = text.charAt(pos);
                if (separator == ',') {
                    pos++;
                    continue;
                }
                if (separator == '}') {
                    pos++;
                    return map;
                }
                throw error("Expected ',' or '}'");
            }
        }

        private List<Object> parseArray() throws IOException {
            List<Object> list = new ArrayList<>();
            pos++; // consume '['
            ws();
            if (pos < text.length() && text.charAt(pos) == ']') {
                pos++;
                return list;
            }
            while (true) {
                list.add(parseValue());
                ws();
                if (pos >= text.length()) {
                    throw error("Unterminated array");
                }
                char separator = text.charAt(pos);
                if (separator == ',') {
                    pos++;
                    continue;
                }
                if (separator == ']') {
                    pos++;
                    return list;
                }
                throw error("Expected ',' or ']'");
            }
        }

        private String parseString() throws IOException {
            pos++; // consume opening quote
            StringBuilder out = new StringBuilder();
            while (pos < text.length()) {
                char current = text.charAt(pos);
                if (current == '"') {
                    pos++;
                    return out.toString();
                }
                if (current == '\\') {
                    pos++;
                    if (pos >= text.length()) {
                        break;
                    }
                    char escaped = text.charAt(pos);
                    switch (escaped) {
                        case '"' -> out.append('"');
                        case '\\' -> out.append('\\');
                        case '/' -> out.append('/');
                        case 'b' -> out.append('\b');
                        case 'f' -> out.append('\f');
                        case 'n' -> out.append('\n');
                        case 'r' -> out.append('\r');
                        case 't' -> out.append('\t');
                        case 'u' -> {
                            if (pos + 4 >= text.length()) {
                                throw error("Invalid \\u escape");
                            }
                            String hex = text.substring(pos + 1, pos + 5);
                            try {
                                out.append((char) Integer.parseInt(hex, 16));
                            } catch (NumberFormatException e) {
                                throw error("Invalid \\u escape");
                            }
                            pos += 4;
                        }
                        default -> throw error("Invalid escape '\\" + escaped + "'");
                    }
                    pos++;
                } else {
                    out.append(current);
                    pos++;
                }
            }
            throw error("Unterminated string");
        }

        private Object parseNumber() throws IOException {
            int start = pos;
            if (pos < text.length() && text.charAt(pos) == '-') {
                pos++;
            }
            while (pos < text.length() && Character.isDigit(text.charAt(pos))) {
                pos++;
            }
            if (pos < text.length() && text.charAt(pos) == '.') {
                pos++;
                while (pos < text.length() && Character.isDigit(text.charAt(pos))) {
                    pos++;
                }
            }
            if (pos < text.length() && (text.charAt(pos) == 'e' || text.charAt(pos) == 'E')) {
                pos++;
                if (pos < text.length() && (text.charAt(pos) == '+' || text.charAt(pos) == '-')) {
                    pos++;
                }
                while (pos < text.length() && Character.isDigit(text.charAt(pos))) {
                    pos++;
                }
            }
            String literal = text.substring(start, pos);
            try {
                return normalizeNumber(new BigDecimal(literal));
            } catch (NumberFormatException e) {
                throw error("Invalid number '" + literal + "'");
            }
        }
    }

    public static final class NotFoundException extends RuntimeException {
        public NotFoundException(String collection, int id) {
            super(collection + " " + id + " was not found.");
        }
    }
}